### ISSUE TITLE
syntax error when running code

### ISSUE THREAD

**Issue by yertle** [maxdup/amiibozos#3]
This is what I see the when I try to run the code. Any ideas? I am not a python developer ;)

I did install the requirements.

```
$ python tokenify.py
  File "tokenify.py", line 26
    def show_info(scene: Scene):
                       ^
SyntaxError: invalid syntax
```

Thanks!
-Brian

**Comment by maxdup** [comment]
Hey Brian,
This is probably due to using an outdated version of python. The syntax highlighted here was introduced in python 3.5 which is quite old already.

The `python --version` command can tell you which version of python you are using. My advice would be to update your python to something more modern like 3.8+.

I'm going to close the issue as I don't think it's a problem with the project but feel free to let me know if you need more help.

**Comment by yertle** [comment]
Ok, got it. I just installed python3. I’ll try a newer version. Thanks for the quick help!-BrianOn Jan 27, 2023, at 4:21 PM, Maxime Dupuis ***@***.***> wrote:﻿
Hey Brian,
This is probably due to using an outdated version of python. The syntax highlighted here was introduced in python 3.5 which is quite old already.
The python --version command can tell you which version of python you are using. My advice would be to update your python to something more modern like 3.8+.
I'm going to close the issue as I don't think it's a problem with the project but feel free to let me know if you need more help.

**Comment by yertle** [comment]
I had python 2.7 and python3 installed. 'which python' was routing to python2.7. I aliased it and fixed it. 'python --version' shows 3.8.1.0 now.

I'm now getting a new error.

`$ python tokenify.py
Traceback (most recent call last):
  File "tokenify.py", line 11, in <module>
    from svg_extrude.model import Scene, Shape, Group, ColorSet, Polygon, Point, Color
  File "/home/bnehring/.local/lib/python3.8/site-packages/svg_extrude/__init__.py", line 1, in <module>
    from .output_writer import OutputWriter
  File "/home/bnehring/.local/lib/python3.8/site-packages/svg_extrude/output_writer.py", line 5, in <module>
    from svg_extrude.model import Shape, Group
  File "/home/bnehring/.local/lib/python3.8/site-packages/svg_extrude/model/__init__.py", line 5, in <module>
    from .shape import Shape
  File "/home/bnehring/.local/lib/python3.8/site-packages/svg_extrude/model/shape.py", line 15, in <module>
    class Shape:
  File "/home/bnehring/.local/lib/python3.8/site-packages/svg_extrude/model/shape.py", line 21, in Shape
    def from_svg_path(cls, svg_path: cjlano_svg.Path, precision: float, *, snap: Optional[float] = None) -> "Shape":
AttributeError: module 'libs.cjlano_svg' has no attribute 'Path'`

Any ideas? Thanks for the tech support ;)

**Comment by maxdup** [comment]
Ah it seems you need to install the dependencies. This is usually done using the `pip install -r requirements.txt` command.
similarly to python, pip can coexist in 2 versions (2 and 3). Assuming you're on linux, You might have to  `sudo apt install python3-pip` and use the `pip3` command instead.

**Comment by yertle** [comment]
I tried that and it's still not working. I confirmed I have pip3 installed,
ran 'pip3 install -r requirements.txt', and still get the same error when
running tokenize.py

-Brian

**Comment by maxdup** [comment]
Damn you're right, I had forgot how messy this project got because of the other projects it was based on.
This is going to be a bit of a detour but you'll need to reinstall the `svg_extrude` dependency manually from source (+ its git submodules).

So first:
`pip uninstall svg_extrude`
then
`cd ~/` (or directory of your choosing)
`git clone https://github.com/maxdup/svg_extrude.git`
`cd svg_extrude`
`git submodule init`
`git submodule update`
`pip install .`

I've opened a separate issue as a reminder.

Also note: You need OpenSCAD installed.

Btw, do let me know if you have svgs to contribute in the future :) Have fun using amiibozos

**Comment by yertle** [comment]
Ok, got it, I’ll work on this tomorrow. I’m fine with Linux dev, just never
do any python stuff.

I’m planning to design some Zelda coins, and am happy to add them to the
repo when I’m done.

**Comment by yertle** [comment]
getting further.

$ python tokenify.py
Rendering to models/smash_banjo.stl
Traceback (most recent call last):
  File "tokenify.py", line 245, in <module>
    make_amiibozo(front, series['backside'])
  File "tokenify.py", line 236, in make_amiibozo
    render_faces(writer, scene_front, scene_back)
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File
"/home/bnehring/.local/lib/python3.8/site-packages/svg_extrude/scad/renderer.py",
line 38, in render_file
    subprocess.run(command, capture_output=True, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'openscad'

Does it need a directory called openscad, or is this another missing
dependency?

-Brian

**Comment by maxdup** [comment]
Yeah you'll need to install OpenSCAD which enables us to create 3d meshes through programming.
`sudo apt-get install openscad`

This will give you the `openscad` command which python intends to call.

**Comment by yertle** [comment]
Openscad is having a dependency problem in Ubuntu. I searched and others that have this issue didn’t have a resolution. Unfortunately I think I am going to give up on this project. I am going to try modeling the coins by hand instead of automating it. Thanks, I appreciate the help!-BrianOn Jan 29, 2023, at 10:16 AM, Maxime Dupuis ***@***.***> wrote:﻿
Yeah you'll need to install OpenSCAD which enables us to create 3d meshes through programming.
sudo apt-get install openscad
This will give you the openscad command which python intends to call.

**Comment by maxdup** [comment]
Ah that's a shame, I think you would have enjoyed OpenSCAD. Good luck with the modeling :)

**Comment by yertle** [comment]
We can keep debugging if you're game. But feel free to quit when it gets
tiring.

This is my current error:
$ python tokenify.py
Rendering to models/smash_banjo.stl
Traceback (most recent call last):
  File "tokenify.py", line 245, in <module>
    make_amiibozo(front, series['backside'])
  File "tokenify.py", line 236, in make_amiibozo
    render_faces(writer, scene_front, scene_back)
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File
"/home/bnehring/.local/lib/python3.8/site-packages/svg_extrude/scad/renderer.py",
line 38, in render_file
    subprocess.run(command, capture_output=True, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['openscad', '-o',
'models/smash_banjo.stl', '/tmp/tmpcd78gdqo.scad']' returned non-zero exit
status 127.

When I run openscad I see this, which I would guess is the problem:
$ openscad
openscad: error while loading shared libraries: libQt5Core.so.5: cannot
open shared object file: No such file or directory

I tried a few things, like these, and they didn't help:
https://ask.fedoraproject.org/t/openscad-does-not-find-shared-object-file-libqt5core-so-5-on-fedora-31/8690
https://ask.fedoraproject.org/t/openscad-does-not-find-shared-object-file-libqt5core-so-5-on-fedora-31/8690

I'm using Ubuntu 20.04.5 LTS.

-Brian
